### ISSUE TITLE
Could your team plant to update SoupX for Seurat_v3.0 ?

### ISSUE THREAD

**Issue by Suzuk1** [constantAmateur/SoupX#10]
Hi,

I am using SoupX for my 10X data and it seems to be nice for reducing soup !

Recently, Seurat_v3.0 was pre-released accompanied with big upgrading of 10xCellRanger.
Seurat_v3.0：https://satijalab.org/seurat/
CellRanger3.0：https://www.10xgenomics.com/solutions/single-cell/

I want to use SoupX with Seurat_v3.0 .But I can not use new 10x data in SoupX now.
Could your team plant to update SoupX for Seurat_v3.0 ?

Best regards,

**Comment by constantAmateur** [comment]
The latest update to the package should allow you to load cellranger v3 output with the `load10X` function as before.  I'm not really sure what you are referring to with Seurat V3.  The output of SoupX is a corrected sparse matrix which can be loaded into any downstream analysis package, including any version of Seurat, instead of the uncorrected input.
