### ISSUE TITLE
Error in inferNonExpressedGenes(scl) : could not find function "inferNonExpressedGenes"

### ISSUE THREAD

**Issue by molybdenumt** [constantAmateur/SoupX#20]
I keep getting the error:
Error in inferNonExpressedGenes(scl) : 
  could not find function "inferNonExpressedGenes"
But when I pull up the help document, using "?inferNonExpressedGenes" it shows the document. 

I tried the function in R version 3.5.1 and R version 3.6.1. I'm not sure what is going on.

**Comment by constantAmateur** [comment]
The inferNonExpressed genes should no longer be directly called by the user and is not provided to the user, that is why you are getting a message that it could not be found.

I decided to remove it because people were misusing it as an automated gene detection function, when it was intended as a heuristic.  As you have noticed, the help file is still available.

**Comment by molybdenumt** [comment]
What is the function to replace it? I'm trying to figure out which genes to use as soup. It would be good to be able to get the expression level of genes and then I can consider which genes to use as soup.

**Comment by constantAmateur** [comment]
The vignette shows how to look at the most expressed genes in the background `head(sc$soupProfile[order(sc$soupProfile$est, decreasing = TRUE), ], n = 20)`

But these are not necessarily the most useful.  The `plotMarkerDistribution` function will show a suggestion of 20 potentially useful genes when run without specifying geneSets.  But it is up to you to pick something useful to your use case.  

See also the FAQ in the main Readme.
