### ISSUE TITLE
What count matrix should be used with SoupX?

### ISSUE THREAD

**Issue by tkapello** [constantAmateur/SoupX#62]
Hi,

 thanks for this useful tool, I want to try it on my dataset. I have a Seurat object an want to remove background noise to improve my clustering. Which count table would you recommend? Raw or normalized counts? And, if I understand correctly the vignette, one can continue downstream analysis with the output?

Thanks in advance!

**Comment by constantAmateur** [comment]
You must input raw count matricies.  Ideally you should start from the cellranger output folder for 10X data.  This is because the empty droplets are used to calculate the composition of the contamination.

The results of `adjustCounts` can be used as input for Seurat or any other analysis.  The [vignette](https://rawcdn.githack.com/constantAmateur/SoupX/6be48cdb0950ed145a3ca6cf235ec2c24d626f81/inst/doc/pbmcTutorial.html) has more details.
