### ISSUE TITLE
detailed vignette cannot be opened

### ISSUE THREAD

**Issue by guanlinW** [constantAmateur/SoupX#77]
Hi there,
many thanks for developing this wonderful tool.
I met this problem when I want to open the vignette:

"

Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

cran.r-project.org

Apache

"

Any ideas,
Thank you very much!

Guanlin

**Comment by krishnaroskin** [comment]
Looks like the module was pulled from CRAN: https://cran.r-project.org/web/packages/SoupX/index.html

**Comment by ChangxuFan** [comment]
I would highly appreciate it if the vignette is available somewhere else independent from CRAN. 
Thanks~

**Comment by kanefos** [comment]
show me da vignette

**Comment by constantAmateur** [comment]
I've updated the link to the vignette to point somewhere other than CRAN (link [here](https://rawcdn.githack.com/constantAmateur/SoupX/204b602418df12e9fdb4b68775a8b486c6504fe4/inst/doc/pbmcTutorial.html)).

The CRAN "issue" has been fixed in the latest release so the CRAN link should work again soon too.
