### ISSUE TITLE
Invalid cluster specification

### ISSUE THREAD

**Issue by peachgong** [constantAmateur/SoupX#85]
when I run setCluster function as follow:

clusters<-c(as.matrix(FemaleM@meta.data$seurat_clusters))
barcodes<-c(as.matrix(rownames(FemaleM@meta.data)))
sc = setClusters(sc, setNames(clusters, barcodes))

It always gets an error say 
"Error in setClusters(sc, setNames(clusters, barcodes)) : 
  Invalid cluster specification.  See help."

FemaleM is a Seurat object in which I have clustered the data and had specific cluster information.

Any idea for the error?

**Comment by hothri** [comment]
@peachgong Hi, Have you solved this? Which cluster information did you use?

**Comment by peachgong** [comment]
Yes. I think so. I later use that from cellranger instead of seurat object

**Comment by mihem** [comment]
Using the Seurat information works for me (e.g. in case you run cellranger with --nosecondary, which I often due to save time). It's important that you create the Seurat object with minmal restriction, so that you end up with the same dims, so e.g.

`CreateSeuratObject(sc, min.cells = 0, min.features = 0)`

which is the default, but in usually you select min.cells 3 and min.features = 200 as suggested in the Seurat vignette.

**Comment by domenico-somma** [comment]
Thanks for the suggestion, it solved for me as well. 
I was wondering whether they changed SoupX behaviour or is possible to make it work even if there are a different number of cells between the Seurat object and the original raw data.
